dbt-labs/dbt-core-bundles

release_creation/snapshot/download.sh
release_creation/snapshot/requirements/v1.4.latest.requirements.txt

Accidentally merged prior PR with broken requirements installation.

add wheel and trino to 1.4

---

.github/workflows/integration.yml
.github/workflows/release_bundle.yml
.github/workflows/scheduled_releases.yml
install_snapshot.sh
release_creation/snapshot/requirements/v1.4.pre.requirements.txt
release_creation/snapshot/requirements/v1.5.pre.requirements.txt
release_creation/snapshot/test_archive_install.sh
test/integration/snapshot/test_create.py

Schedule the release of bundles

Add scheduled_releases.yml workflow

---

.github/workflows/integration.yml
.github/workflows/release_bundle.yml
.github/workflows/scheduled_releases.yml

Cleans up workflows to include input types, renames snapshot -> bundle more completely plus a bit of formatting.

clean up workflows

---

.github/workflows/integration.yml
.github/workflows/release_bundle.yml
.github/workflows/scheduled_releases.yml
install_snapshot.sh
release_creation/snapshot/requirements/v1.4.latest.requirements.txt
release_creation/snapshot/requirements/v1.4.pre.requirements.txt
test/integration/snapshot/test_create.py
test/test_requirements.txt
test/unit/snapshot/test_snapshot_config.py

Some changes for tidying up versions etc.

Minor clean up of code

---

.github/workflows/integration.yml
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.5.pre.requirements.txt
release_creation/bundle/requirements/v1.6.pre.requirements.txt
test/integration/bundle/test_create.py

Increment pyodbc to support py3.11

---

release_creation/github_client/releases.py
release_creation/main.py
test/integration/github_client/test_get_latest_bundle_release.py
test/unit/github_client/test_releases.py

resolves #36 
This will normalize all pre release tags to a single "pre" tag.

Standardize pre release suffixes

---

.github/workflows/release_bundle.yml
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/github_client/releases.py
release_creation/main.py
release_creation/release_logger.py

Add extra libxml deps to fix:
```
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [4 lines of output]
<string>:67: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Building lxml version 4.9.3.
Building without Cython.
Error: Please make sure the libxml2 and libxslt development packages are installed.
[end of output]
```

Add libxml deps

---

release_creation/bundle/requirements/v1.4.latest.requirements.txt
release_creation/bundle/requirements/v1.4.pre.requirements.txt
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.5.pre.requirements.txt
release_creation/bundle/requirements/v1.6.pre.requirements.txt

Reverts dbt-labs/dbt-core-bundles#57

Revert "Pin databricks-sdk<0.2"

---

.github/scripts/swap_release_tags.sh
.github/workflows/release_dev_bundle.yml
.github/workflows/release_draft_bundle.yml
release_creation/github_client/create_release.py
release_creation/github_client/get_release.py
release_creation/main.py
test/unit/github_client/test_create_release.py
test/unit/github_client/test_get_release.py
test/unit/test_main.py

Follow on PR to address issues with creating the dev release.

Simplify update workflow

---

release_creation/bundle/requirements/v1.6.latest.requirements.txt
release_creation/bundle/requirements/v1.6.pre.requirements.txt

- add dbt-fabric to 1.6 bundles

Add dbt-fabric to 1.6 bundles

---

release_creation/bundle/requirements/v1.0.latest.requirements.txt

unpin snowflake-connector-python

Fix sf connector version issues in 1.0.latest

---

release_creation/bundle/requirements/v1.0.latest.requirements.txt

- Simplify update workflow (#83)
- add dbt-fabric to 1.6 bundles (#84)
- Pyarrow build broken (#86)
- unpin snowflake-connector-python
- unpin snowflake-connector-python (#91)
- test adding chardet

Test adding chardet

---

release_creation/bundle/requirements/v1.4.latest.requirements.txt
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.6.latest.requirements.txt
release_creation/bundle/requirements/v1.7.latest.requirements.txt
release_creation/bundle/requirements/v1.7.pre.requirements.txt

related to https://github.com/apache/arrow/pull/38608

per pyarrow upstream

---

release_creation/bundle/requirements/v1.6.latest.requirements.txt

- Pin to dbt-fabric in 1.6.latest.requirements.txt

Pin dbt-fabric to 1.6.0

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt

- Pin to dbt-fabric in 1.7.latest.requirements.txt

Pin dbt-fabric to 1.7.0

---

release_creation/bundle/requirements/v1.4.latest.requirements.txt
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.6.latest.requirements.txt
release_creation/bundle/requirements/v1.7.latest.requirements.txt

- set upper bound on google-api-core

set upper bound on google-api-core

---

.github/workflows/scheduled_releases.yml
release_creation/bundle/requirements/v0.0.latest.requirements.txt
release_creation/bundle/requirements/v1.8.latest.requirements.txt
test/integration/bundle/test_create.py

add 1.8.0 latest to workflows, tests, and requirements

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt
release_creation/bundle/requirements/v1.8.latest.requirements.txt
release_creation/bundle/requirements/v1.8.pre.requirements.txt

- add dbt-athena-community to 1.7 & 8 bundles

Add athena to bundles

---

.github/workflows/close-stale-issues.yml

add workflow to close stale PRs and issues

Add workflow to close stale PRs & Issues

---

release_creation/bundle/requirements/v1.2.latest.requirements.txt
release_creation/bundle/requirements/v1.3.latest.requirements.txt

Fix build error for python3.9
https://github.com/dbt-labs/dbt-core-bundles/actions/runs/11040294144/job/30668229444#step:7:2993
https://stackoverflow.com/questions/40845304/runtimewarning-numpy-dtype-size-changed-may-indicate-binary-incompatibility

fix 1.2/1.3 numpy error
