.github/workflows/release_snapshot.yml
release_creation/main.py
release_creation/snapshot/create.py
release_creation/snapshot/download_no_deps.sh

This PR includes a number of overlapping changes:
* Create snapshot_requirments.txt per OS (i.e. mac / linux )
* Test linux install for py 3.8
Not included:
* testing all py/OS combinations

Reflect OS level differences in requirements and install paths

---

.gitignore
release_creation/snapshot/requirements/v1.1.pre.requirements.txt
release_creation/snapshot/requirements/v1.2.pre.requirements.txt
release_creation/snapshot/requirements/v1.3.pre.requirements.txt
release_creation/snapshot/requirements/v1.4.latest.requirements.txt
release_creation/snapshot/requirements/v1.4.pre.requirements.txt

Updating snapshots requirements to include dbt-trino in "pre" snapshots and add a requirement file 1.4.latest

add dbt-trino to pre and add 1.4.latest requirements file

---

.github/workflows/scheduled_releases.yml
release_creation/snapshot/requirements/v1.5.latest.requirements.txt
test/integration/snapshot/test_create.py

Updated the requirements.txt for the 1.5.latest versions.
Note: redshift is pointing to 1.5.1 due to a regression that was patched in 1.5.0

Update for 1.5.0 release

---

.github/workflows/integration.yml
.gitignore
test/unit/snapshot/test_snapshot_config.py
tox.ini

Integration tests are currently failing.  This fixes the failing tests.
**_Tests will still fail on this PR because it uses pull_request_target so it's going to be using the workflow on `main`._**
Manual workflow run to show tests are passing: https://github.com/dbt-labs/dbt-core-snapshots/actions/runs/5082665655

Fix failing integration tests

---

release_creation/snapshot/requirements/v1.0.latest.requirements.txt
release_creation/snapshot/requirements/v1.1.latest.requirements.txt
release_creation/snapshot/requirements/v1.1.pre.requirements.txt
release_creation/snapshot/requirements/v1.2.latest.requirements.txt
release_creation/snapshot/requirements/v1.2.pre.requirements.txt
release_creation/snapshot/requirements/v1.3.latest.requirements.txt
release_creation/snapshot/requirements/v1.3.pre.requirements.txt
release_creation/snapshot/requirements/v1.4.latest.requirements.txt
release_creation/snapshot/requirements/v1.4.pre.requirements.txt
release_creation/snapshot/requirements/v1.5.latest.requirements.txt
release_creation/snapshot/requirements/v1.5.pre.requirements.txt

Pin `snowflake-adapter-python` to _not_ include version 3.0.4 for now.

Force pin snowflake-connector-python

---

release_creation/snapshot/requirements/v1.5.latest.requirements.txt

remove patch version specification for dbt-redshift so we always pull in the latest available when generating the bundles.

remove patch version specification for dbt-redshift

---

release_creation/snapshot/create.py
release_creation/snapshot/requirements/v1.1.latest.requirements.txt
release_creation/snapshot/requirements/v1.1.pre.requirements.txt
release_creation/snapshot/requirements/v1.2.latest.requirements.txt
release_creation/snapshot/requirements/v1.2.pre.requirements.txt
release_creation/snapshot/requirements/v1.3.latest.requirements.txt
release_creation/snapshot/requirements/v1.3.pre.requirements.txt
release_creation/snapshot/requirements/v1.4.latest.requirements.txt
release_creation/snapshot/requirements/v1.4.pre.requirements.txt
release_creation/snapshot/requirements/v1.5.latest.requirements.txt
release_creation/snapshot/requirements/v1.5.pre.requirements.txt
release_creation/snapshot/requirements/v1.6.pre.requirements.txt

pyarrow==12.0.1 was packaged with incorrect metadata, see: https://github.com/apache/arrow/issues/36065
Due to the way we download and install pip packages this throws off pip's validation mechanism.

Address PyArrow package metadata issue

---

.github/workflows/release_bundle.yml
release_creation/bundle/requirements/v1.5.latest.requirements.txt

today a release for `lxml` came out that does make some changes to `Cython` curious if rolling back to `4.9.2` allows build to finish
pypi: https://pypi.org/project/lxml/4.9.3/

new release of lxml today could be causing issues with Cython

---

release_creation/bundle/requirements/v1.4.latest.requirements.txt
release_creation/bundle/requirements/v1.4.pre.requirements.txt
release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.5.pre.requirements.txt
release_creation/bundle/requirements/v1.6.pre.requirements.txt

Starting on July 18, we are seeing this error for some customer runs using dbt-databricks v1.4 + v1.5:
```
HTTPSConnectionPool(host='xxxx.cloud.databricks.com', port=443): Max retries exceeded with url: /sql/1.0/warehouses/xxxx (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1131)')))
```
I suspect this is due to a breaking change in the `databricks-sdk` package, which is a dependency of `dbt-databricks. Supporting evidence:
- `databricks-sdk` was introduced to the `dbt-databricks` plugin a few months ago, and it would have landed in v1.4 + v1.5: https://github.com/databricks/dbt-databricks/pull/307
- `databricks-sdk` put out its 0.2.0 + 0.2.1 releases on July 18: …

Pin databricks-sdk<0.2

---

README.md
release_creation/bundle/requirements/v1.0.latest.requirements.txt
release_creation/bundle/requirements/v1.1.latest.requirements.txt
release_creation/bundle/requirements/v1.1.pre.requirements.txt
release_creation/bundle/requirements/v1.2.latest.requirements.txt
release_creation/bundle/requirements/v1.2.pre.requirements.txt

We want to pull in any critical security updates even if we don't end up publishing a new pypi version.

install 1.2, 1.1 and 1.0 from git branches

---

.github/workflows/scheduled_releases.yml
release_creation/bundle/requirements/v1.6.latest.requirements.txt
release_creation/main.py
test/integration/bundle/test_create.py

resolves #63 
- update workflow and testing to release `1.6.0` instead of `1.6.0b2`
- create `v1.6.latest.requirements.txt` from `v1.6.pre.requirements.txt` and update where appropriate
- pyarrow was removed as `snowflake-connector-python` no longer installs it
- `dbt-databricks` has not released a `1.6.0final`, and is soft pinned to `1.6.0rc3`
- `dbt-bigquery` installs newer minor versions of `grpcio-status` and `pyasn1-modules`
- included `secure-local-storage` extra for `snowflake-connector-python`

1.6.0 final release

---

.github/actions/test_install/action.yml
.github/workflows/release_draft_bundle.yml
.github/workflows/release_new_bundle.yml

Currently if we fail to generate any of the draft bundles we skip the publish step resulting in no bundles being published. Eventually we want to add an intermediate testing step to judge what gets released but for now we just want to release any draft that has been successfully created.

Always release draft bundles

---

release_creation/bundle/bundle_os.py

`macosx_10_10_intel` is an unusual tag that may not be well resolved for all packages.

remove macosx_10_10_intel platform tag

---

.github/workflows/publish_draft_bundle.yml

We install linux dependencies in `release_draft_bundle.yml` that are not installed in `publish_draft_bundle.yml`. In particular, `libsasl2-dev` is not installed, which causes failures during release testing; the wheel for `sasl` cannot be built because it uses `pyproject.toml`. This PR adds the same linux dependencies to both files.

Install linux dependencies in publish_draft_bundle.yml

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt

This will add dbt-fabric to 1.7.latest.requirements.txt, only merge once 1.70 of dbt-fabric has been released

Add dbt-fabric to 1.7

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt

This will allow the newest version of `dbt-fabric~=1.7.0` to be deployed to Cloud. We should only merge this after confirming that the fix (adding `mssql-tools18` to the deploy image) worked in the `1.7.pre` bundle.

Unpin `dbt-fabric~=1.7.0` in the `1.7.latest` bundle

---

.github/dependabot.yml
pyproject.toml
setup.cfg

I configured dependabot for two things:
- pip on the root requirements file (hopefully it doesn't search down `/bundles`
- github actions
While doing this, I noticed that `setup.cfg` had settings that could be merged into `pyproject.toml`. I merged the two files and removed setup.cfg`.

OpsLevel POC: `dependabot.yml`, add python version to `pyproject.toml`

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt
release_creation/bundle/requirements/v1.7.pre.requirements.txt

We were having a weird interaction between different pydantic dep specifications, and pydantic 2 was getting install unexpectedly. This makes that impossible.

Exclude Pydantic 2 from dbt-core 1.7 bundles

---

release_creation/bundle/requirements/v1.5.latest.requirements.txt
release_creation/bundle/requirements/v1.6.latest.requirements.txt
release_creation/bundle/requirements/v1.7.latest.requirements.txt

- add upper/lower bounds to pandas import in v1.7.latest.requirements.txt

add bounds to pandas for 1.7

---

release_creation/bundle/requirements/test.requirements.txt
release_creation/bundle/requirements/v0.0.latest.requirements.txt
release_creation/bundle/requirements/v1.7.latest.requirements.txt
release_creation/bundle/requirements/v1.7.pre.requirements.txt

`dbt-synapse` has a 1.7 pre-release available. This adds the pre-release to the pre-release bundle. `dbt-synapse` has not published a final release yet.

Add dbt-synapse 1.7.0rc1 to the 1.7 pre-release bundle

---

.github/dependabot.yml

The `directory` attribute is not recursive, and cannot take a list. An entry is needed for each directory.

Fix dependabot config file to reference multiple directories

---

.github/workflows/integration.yml
.github/workflows/publish_draft_bundle.yml
.github/workflows/release_draft_bundle.yml
.github/workflows/test_install.yml

`macos-latest` now points to `macos-14-arm64`; it used to point to `macos-12`. There is no `py39` nor `py38` on `macos-14-arm64`.
Pin to `macos-12` for now and discuss long term options to use `macos-14-arm64`, and CI pinning in general.

Pin `macos` test runners to `macos-12`

---

release_creation/bundle/requirements/v1.8.pre.requirements.txt

We released `dbt-adapters==1.1.0rc1`, which is not getting picked up by the `1.8.pre` file because it's soft pinned to the `1.0` minor.

Allow all versions of `dbt-adapters` into the pre file

---

release_creation/bundle/requirements/v1.7.latest.requirements.txt

Need to skip synapse 1.7.4 as it's broken

Update v1.7.latest.requirements.txt to exclude dbt-synapse 1.7.4

---

release_creation/bundle/requirements/v1.0.latest.requirements.txt
release_creation/bundle/requirements/v1.1.latest.requirements.txt
release_creation/bundle/requirements/v1.2.latest.requirements.txt
release_creation/bundle/requirements/v1.3.latest.requirements.txt

`setuptools>=71.0` requires `packages>=24.0` but `dbt-core<1.4` requires `packages<22.0`.

Pin `setuptools` to avoid conflict with `packages` dep in `dbt-core`

---

release_creation/bundle/requirements/v1.0.latest.requirements.txt
release_creation/bundle/requirements/v1.1.latest.requirements.txt

This ensures that the error `numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`, which would otherwise appear when running `dbt --version`, does not occur.

Limit dbt 1.0.latest and 1.1.latest to numpy<2.0.0
